project_id = "jkblxbgnsbosnayxxxgw"

[functions.export-database]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = true

[functions.export-logs]
verify_jwt = true

[functions.payment-stats]
verify_jwt = true